name:                wai-saml2
version:             0.3.0.1
github:              "mbg/wai-saml2"
license:             MIT
author:              "Michael B. Gale"
maintainer:          "github@michael-gale.co.uk"
copyright:           "Copyright (c) Michael B. Gale"

category:            Security
synopsis:            "SAML2 assertion validation as WAI middleware"
description:         "A Haskell library which implements SAML2 assertion validation as WAI middleware"

extra-source-files:
- README.md
- CHANGELOG.md
- tests/data/**

default-extensions:
- OverloadedStrings
- MultiWayIf
- RecordWildCards
- FlexibleInstances

dependencies:
- base >= 4.8 && < 5
- text < 2
- bytestring >= 0.9 && < 0.12
- base64-bytestring >= 0.1 && < 2
- containers >= 0.6 && <0.7
- data-default-class < 1
- http-types < 1
- wai >= 3.0 && < 4
- wai-extra >= 3.0 && < 4
- vault >= 0.3 && < 1
- cryptonite < 1
- x509 < 2
- x509-store < 2
- xml-conduit < 2
- time >= 1.9 && < 2
- mtl >= 2.2.1 && < 3
- c14n >= 0.1.0.1 && < 1

library:
    source-dirs: src
    ghc-options:
    - -W

tests:
  parser:
    main: Parser.hs
    source-dirs: tests
    ghc-options: -Wall -Wcompat
    dependencies:
    - base
    - bytestring
    - filepath
    - pretty-show
    - tasty
    - tasty-golden
    - wai-saml2
    - xml-conduit
